// SPDX-License-Identifier: GPL-2.0+

#include <init.h>
#include <asm/arch-rockchip/bootrom.h>
#include <asm/arch-rockchip/grf_rk3128.h>
#include <asm/arch-rockchip/hardware.h>

#define GRF_BASE	0x20008000

const char * const boot_devices[BROM_LAST_BOOTSOURCE + 1] = {
	[BROM_BOOTSOURCE_EMMC] = "/mmc@1021c000",
	[BROM_BOOTSOURCE_SPINOR] = "/spi@1020c000/flash@0",
	[BROM_BOOTSOURCE_SPINAND] = "/spi@1020c000/flash@0",
	[BROM_BOOTSOURCE_SD] = "/mmc@10214000",
};

#if IS_ENABLED(CONFIG_DEBUG_UART_BOARD_INIT) && defined(CONFIG_DEBUG_UART_BASE)
void board_debug_uart_init(void)
{
	struct rk3128_grf * const grf = (void *)GRF_BASE;
#if CONFIG_DEBUG_UART_BASE == 0x20060000
	enum {
		GPIO2D2_SHIFT		= 4,
		GPIO2D2_MASK		= 3 << GPIO2D2_SHIFT,
		GPIO2D2_UART0_SOUT	= 2,

		GPIO2D3_SHIFT		= 6,
		GPIO2D3_MASK		= 3 << GPIO2D3_SHIFT,
		GPIO2D3_UART0_SIN	= 2,
	};

	rk_clrsetreg(&grf->gpio1b_iomux,
		     GPIO2D2_MASK | GPIO2D3_MASK,
		     GPIO2D2_UART0_SOUT << GPIO2D2_SHIFT |
		     GPIO2D3_UART0_SIN << GPIO2D3_SHIFT);
#elif CONFIG_DEBUG_UART_BASE == 0x20064000
	enum {
		GPIO1B1_SHIFT		= 2,
		GPIO1B1_MASK		= 3 << GPIO1B1_SHIFT,
		GPIO1B1_UART1_SOUT	= 2,

		GPIO1B2_SHIFT		= 4,
		GPIO1B2_MASK		= 3 << GPIO1B2_SHIFT,
		GPIO1B2_UART1_SIN	= 2,

	};

	rk_clrsetreg(&grf->gpio1b_iomux,
		     GPIO1B1_MASK | GPIO1B2_MASK,
		     GPIO1B1_UART1_SOUT << GPIO1B1_SHIFT |
		     GPIO1B2_UART1_SIN << GPIO1B2_SHIFT);
#elif CONFIG_DEBUG_UART_BASE == 0x20068000
#if IS_ENABLED(CONFIG_ROCKCHIP_USB_UART)
	enum {
		UTMI_TERMSELECT_SHIFT = 6,
		UTMI_TERMSELECT_MASK = 1 << UTMI_TERMSELECT_SHIFT,
		UTMI_TERM_HS = 0,
		UTMI_TERM_FS,

		UTMI_XCVRSELECT_SHIFT = 4,
		UTMI_XCVRSELECT_MASK = 3 << UTMI_XCVRSELECT_SHIFT,
		UTMI_XCVR_HS = 0,
		UTMI_XCVR_FS,
		UTMI_XCVR_LS,

		UTMI_OPMODE_SHIFT = 2,
		UTMI_OPMODE_MASK = 3 << UTMI_OPMODE_SHIFT,
		UTMI_OPMODE_NORMAL = 0,
		UTMI_OPMODE_NON_DRIVING,
		UTMI_OPMODE_NORMAL_WO_SYNC,

		UTMI_SUSPEND_N_SHIFT = 1,
		UTMI_SUSPEND_N_MASK = 1 << UTMI_SUSPEND_N_SHIFT,
		UTMI_SUSPEND_ENABLE = 0,
		UTMI_SUSPEND_DISABLE,

		USBPHY_SOFT_CON_SEL_SHIFT = 0,
		USBPHY_SOFT_CON_SEL_MASK = 1 << USBPHY_SOFT_CON_SEL_SHIFT,
		USBPHY_SOFT_CON_DISABLE = 1,
		USBPHY_SOFT_CON_ENABLE,
	};

	rk_clrsetreg(&grf->uoc0_con0,
		     UTMI_TERMSELECT_MASK | UTMI_OPMODE_MASK |
		     UTMI_SUSPEND_N_MASK | USBPHY_SOFT_CON_SEL_MASK,
		     UTMI_TERM_FS << UTMI_TERMSELECT_SHIFT |
		     UTMI_XCVR_FS << UTMI_XCVRSELECT_SHIFT |
		     UTMI_OPMODE_NON_DRIVING << UTMI_OPMODE_SHIFT |
		     UTMI_SUSPEND_ENABLE << UTMI_SUSPEND_N_SHIFT |
		     USBPHY_SOFT_CON_ENABLE << USBPHY_SOFT_CON_SEL_SHIFT);

	enum {
		BYPASSSEL0_SHIFT = 13,
		BYPASSSEL0_MASK = 1 << BYPASSSEL0_SHIFT,
		BYPASSSEL0_DISABLE = 0,
		BYPASSSEL0_ENABLE = 1,

		BYPASSDMEN0_SHIFT = 12,
		BYPASSDMEN0_MASK = 1 << BYPASSDMEN0_SHIFT,
		BYPASSDMEN0_DISABLE = 0,
		BYPASSDMEN0_ENABLE,

		OTGPHYDISABLE_SHIFT = 10,
		OTGPHYDISABLE_MASK = 1 << OTGPHYDISABLE_SHIFT,
		OTGPHY_ENABLE = 0,
		OTGPHY_DISABLE,
	};

	rk_clrsetreg(&grf->uoc1_con4,
		     BYPASSSEL0_MASK | BYPASSDMEN0_MASK |
		     OTGPHYDISABLE_MASK,
		     BYPASSSEL0_ENABLE << BYPASSSEL0_SHIFT |
		     BYPASSDMEN0_ENABLE << BYPASSDMEN0_SHIFT |
		     OTGPHY_DISABLE << OTGPHYDISABLE_SHIFT);
#else
	enum {
		GPIO1C2_SHIFT		= 4,
		GPIO1C2_MASK		= 3 << GPIO1C2_SHIFT,
		GPIO1C2_UART2_TX	= 2,

		GPIO1C3_SHIFT		= 6,
		GPIO1C3_MASK		= 3 << GPIO1C3_SHIFT,
		GPIO1C3_UART2_RX	= 2,
	};

	rk_clrsetreg(&grf->gpio1c_iomux,
		     GPIO1C3_MASK | GPIO1C2_MASK,
		     GPIO1C2_UART2_TX << GPIO1C2_SHIFT |
		     GPIO1C3_UART2_RX << GPIO1C3_SHIFT);
#endif //IS_ENABLED(CONFIG_ROCKCHIP_USB_UART)
#endif
}
#endif //IS_ENABLED(CONFIG_DEBUG_UART_BOARD_INIT) && defined(CONFIG_DEBUG_UART_BASE)

#if !IS_ENABLED(CONFIG_TPL_BUILD)
int arch_cpu_init(void)
{
#if IS_ENABLED(CONFIG_SPL_BUILD)
#if IS_ENABLED(CONFIG_ROCKCHIP_DISABLE_FORCE_JTAG)
	struct rk3128_grf * const grf = (void *)GRF_BASE;

	/* don't force jtag on sdmmc/uart2 iomux */
	rk_clrreg(&grf->soc_con0, BIT(8));
#endif
#endif
	return 0;
}
#endif
